# -*- coding: utf-8 -*-
"""BACO_Station_Vibe_Recommender_NEW.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hwmClOigReqt4PdRM-2D95mzpGu4xtng

# BACO Station — Vibe Music Recommender

**Course:** Projects in Programming & AI
**Group:** S2 BACO Station
**Milestone 5 — Frontend Prototype**

---

## What is BACO Station?

BACO Station is an interactive music recommender. Instead of asking the user to fiddle with technical sliders ("set energy to 0.7"), we ask a short **vibe quiz** — Hogwarts house, season, dream city, texting style, party persona, and so on. Each answer maps to musical features (energy, valence, genre, mood), and the system scores songs in our Spotify-style dataset to return a **top pick** plus a small **playlist**.

For the top pick we also fetch the **real album cover** and a **30-second audio preview** from Apple's free iTunes Search API, so the prototype feels close to a real product.

This notebook is the **frontend prototype** for Milestone 5. It is a live, interactive page (not a wireframe) built with `ipywidgets` + `pandas`.

> Tip: run all cells from top to bottom, then play with the widgets at the bottom.

## 1. Setup — import the libraries we need

We use `pandas` for the dataset, `ipywidgets` for the user interface, and `requests` to call the iTunes Search API. If you are running this in a fresh environment (Colab or a new Jupyter install), uncomment the install line below.
"""

# Uncomment if you need to install:
# !pip install pandas ipywidgets requests --quiet

import pandas as pd
import ipywidgets as widgets
import requests
from IPython.display import display, HTML, clear_output, Audio

# If you are on Google Colab, uncomment these two lines so widgets render:
from google.colab import output
output.enable_custom_widget_manager()

"""
# 2. Backend + Dataset Pipeline (NEW)

This project now includes a real backend/data layer instead of a hardcoded Python list.

### What this section does
- Downloads a large Spotify dataset (100k+ songs)
- Stores the dataset in a SQLite database
- Loads the data from SQL into pandas
- Creates a reusable backend workflow

This satisfies the course requirement for:
- Backend component
- Database usage
- Larger dataset
- Data storage + retrieval pipeline
"""

import pandas as pd
import sqlite3
from pathlib import Path

DB_NAME = "spotify_music.db"
CSV_URL = "https://huggingface.co/datasets/sfiore/spotify-tracks-dataset/resolve/main/dataset.csv"
# Download a larger dataset (100k+ rows)
songs = pd.read_csv(CSV_URL)

# Clean column names
songs.columns = [c.lower().strip() for c in songs.columns]

# Keep only useful columns if they exist
wanted_columns = [
    "track_name",
    "artists",
    "track_genre",
    "danceability",
    "energy",
    "valence",
    "tempo",
    "acousticness",
    "instrumentalness",
    "speechiness",
    "liveness",
    "popularity"
]

existing_columns = [c for c in wanted_columns if c in songs.columns]
songs = songs[existing_columns].dropna()

# Save to SQLite database
conn = sqlite3.connect(DB_NAME)
songs.to_sql("spotify_tracks", conn, if_exists="replace", index=False)

# Load back from SQL (backend retrieval)
songs = pd.read_sql_query(
    "SELECT * FROM spotify_tracks LIMIT 50000",
    conn
)

# Rename columns for consistency with recommendation logic and display functions
songs = songs.rename(columns={
    "track_name": "name",
    "artists": "artist",
    "track_genre": "genre"
})

# Function to assign mood to each song based on energy and valence
def assign_mood_to_song(row):
    e = row["energy"]
    v = row["valence"]

    if e >= 0.78 and v >= 0.78:
        return "Energetic"
    if e >= 0.65 and v >= 0.55:
        return "Happy"
    if e >= 0.65 and v < 0.55:
        return "Energetic"
    if e < 0.40 and v < 0.40:
        return "Sad"
    if e < 0.40:
        return "Focus"
    if v < 0.40:
        return "Sad"
    if e >= 0.45 and v >= 0.65:
        return "Chill"
    if e < 0.45 and v >= 0.55:
        return "Happy"
    return "Chill"

# Apply the mood assignment
songs["mood"] = songs.apply(assign_mood_to_song, axis=1)

print("Dataset loaded successfully")
print("Rows:", len(songs))
print("Columns:", list(songs.columns))
songs.head()

"""
# 3. Exploratory Data Analysis (NEW)

The recommender now includes real data analytics and visualization.

### Added analytics
- Feature distributions
- Genre analysis
- Clustering analysis
- Mood prediction preparation
- Visualization dashboard

These sections satisfy the course requirement for:
- Data analytics
- Data visualization
- Useful insights from the dataset
"""

import matplotlib.pyplot as plt
import seaborn as sns

numeric_features = [
    "danceability",
    "energy",
    "valence",
    "tempo",
    "acousticness"
]

songs[numeric_features].hist(figsize=(12, 8))
plt.suptitle("Distribution of Spotify Audio Features")
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 6))

sample_df = songs.sample(min(3000, len(songs)))

sns.scatterplot(
    data=sample_df,
    x="energy",
    y="valence",
    hue="genre",
    alpha=0.6,
    legend=False
)

plt.title("Genre Distribution by Energy and Valence")
plt.xlabel("Energy")
plt.ylabel("Valence")
plt.show()

"""
# 4. Machine Learning — Song Clustering (NEW)

We use K-Means clustering to group songs into vibe categories based on their audio features.

This adds a genuine machine learning / analytics component to the project.
"""

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

features = [
    "danceability",
    "energy",
    "valence",
    "tempo",
    "acousticness"
]

cluster_df = songs[features].dropna().copy()

scaler = StandardScaler()
scaled = scaler.fit_transform(cluster_df)

kmeans = KMeans(n_clusters=5, random_state=42)
cluster_df["cluster"] = kmeans.fit_predict(scaled)

songs.loc[cluster_df.index, "cluster"] = cluster_df["cluster"]

plt.figure(figsize=(10, 6))

sns.scatterplot(
    data=songs.sample(min(4000, len(songs))),
    x="energy",
    y="valence",
    hue="cluster",
    palette="deep",
    alpha=0.7
)

plt.title("K-Means Song Clusters")
plt.show()

"""
# 5. Interactive Visualization Dashboard (NEW)

This dashboard gives users insight into:
- Music mood distributions
- Audio feature relationships
- Cluster behavior
- Genre characteristics

This satisfies the visualization requirement for the final presentation.
"""

import plotly.express as px

fig = px.scatter(
    songs.sample(min(5000, len(songs))),
    x="danceability",
    y="energy",
    color="valence",
    hover_data=["track_name"] if "track_name" in songs.columns else None,
    title="Interactive Spotify Audio Feature Map"
)

fig.show()

"""# 6. Hosting / Live Demo Instructions (NEW)

For the presentation, deploy the notebook or convert it into a web app using one of these options:

### Recommended options
1. Streamlit Cloud
2. Hugging Face Spaces
3. Render
4. Railway

### Simplest deployment workflow
```bash
pip install streamlit
streamlit run app.py
```

Then upload the project to GitHub and connect it to Streamlit Cloud.

This gives you a public URL that satisfies the course requirement.

## 3. Vibe quiz definition

We define each question and its options in a single Python list. Every option carries weights for:

- `energy` (target 0–1) — how intense the user's music should be
- `valence` (target 0–1) — how positive/happy the user's music should be
- `genres` — bonus weights per matching genre
- `moods` — bonus weights per matching mood

When the user answers, we **average** the energy/valence weights across questions and **sum** the genre/mood weights to build the user's musical profile.
"""

quiz = [
    {
        "title": "Which Hogwarts house feels most like you?",
        "options": [
            {"label": "Gryffindor — bold, loud, main character",       "w": {"energy": 0.85, "valence": 0.70, "genres": {"Rock": 3, "Pop": 2, "Hip-Hop": 2}, "moods": {"Energetic": 3, "Happy": 1}}},
            {"label": "Slytherin — cool, sharp, low-key powerful",     "w": {"energy": 0.70, "valence": 0.30, "genres": {"Hip-Hop": 3, "Electronic": 3, "R&B": 2}, "moods": {"Energetic": 2, "Chill": 1}}},
            {"label": "Ravenclaw — thoughtful, curious, in your head", "w": {"energy": 0.30, "valence": 0.40, "genres": {"Indie": 3, "Classical": 3, "Jazz": 2}, "moods": {"Focus": 3, "Chill": 1}}},
            {"label": "Hufflepuff — warm, soft, comfort-food coded",   "w": {"energy": 0.45, "valence": 0.85, "genres": {"Pop": 2, "Indie": 2, "R&B": 2}, "moods": {"Happy": 3, "Chill": 2}}},
        ],
    },
    {
        "title": "Pick your current aesthetic",
        "options": [
            {"label": "Cottagecore — sundress, sourdough, fields",        "w": {"energy": 0.35, "valence": 0.75, "genres": {"Indie": 3, "Classical": 2, "Pop": 1}, "moods": {"Happy": 2, "Chill": 2}}},
            {"label": "Dark academia — tweed, candles, old library",      "w": {"energy": 0.30, "valence": 0.30, "genres": {"Classical": 3, "Indie": 2, "Jazz": 2}, "moods": {"Focus": 3, "Sad": 1}}},
            {"label": "Y2K — glitter, low-rise, butterfly clips",         "w": {"energy": 0.85, "valence": 0.85, "genres": {"Pop": 3, "Electronic": 2, "Hip-Hop": 2}, "moods": {"Energetic": 2, "Happy": 3}}},
            {"label": "Clean girl — slicked back, gold hoops, matcha",    "w": {"energy": 0.45, "valence": 0.65, "genres": {"Pop": 2, "R&B": 2, "Indie": 2}, "moods": {"Chill": 3, "Happy": 1}}},
        ],
    },
    {
        "title": "Pick a season that feels like you right now",
        "options": [
            {"label": "Spring — new crush, green, light",         "w": {"energy": 0.55, "valence": 0.85, "genres": {"Pop": 2, "Indie": 2}, "moods": {"Happy": 3}}},
            {"label": "Summer — sunburn, party, no plans",        "w": {"energy": 0.85, "valence": 0.80, "genres": {"Pop": 2, "Hip-Hop": 2, "Electronic": 2}, "moods": {"Energetic": 2, "Happy": 2}}},
            {"label": "Autumn — sweater weather, long walks",     "w": {"energy": 0.45, "valence": 0.40, "genres": {"Indie": 3, "R&B": 2, "Jazz": 1}, "moods": {"Chill": 3, "Sad": 1}}},
            {"label": "Winter — quiet, candle, big feelings",     "w": {"energy": 0.20, "valence": 0.20, "genres": {"Classical": 3, "Indie": 2, "R&B": 1}, "moods": {"Sad": 2, "Focus": 2}}},
        ],
    },
    {
        "title": "If you had to move tomorrow…",
        "options": [
            {"label": "Paris — slow mornings, cafés, jazz",            "w": {"energy": 0.40, "valence": 0.60, "genres": {"Jazz": 3, "Indie": 2, "Classical": 2}, "moods": {"Chill": 3, "Happy": 1}}},
            {"label": "Tokyo — neon, vending machines, 7-Elevens",     "w": {"energy": 0.85, "valence": 0.65, "genres": {"Electronic": 3, "Pop": 2, "Hip-Hop": 2}, "moods": {"Energetic": 3}}},
            {"label": "New York — bagels, basslines, never sleeps",    "w": {"energy": 0.80, "valence": 0.55, "genres": {"Hip-Hop": 3, "R&B": 2, "Rock": 1}, "moods": {"Energetic": 2, "Chill": 1}}},
            {"label": "Reykjavik — cold air, glaciers, Northern Lights","w": {"energy": 0.25, "valence": 0.30, "genres": {"Indie": 2, "Classical": 3, "Electronic": 1}, "moods": {"Focus": 2, "Sad": 2}}},
        ],
    },
    {
        "title": "Your dream Saturday night looks like…",
        "options": [
            {"label": "Out dancing — with friends, loud, sweaty",      "w": {"energy": 0.90, "valence": 0.75, "genres": {"Electronic": 3, "Hip-Hop": 2, "Pop": 2}, "moods": {"Energetic": 3}}},
            {"label": "Cozy at home — movie, blanket, snacks",         "w": {"energy": 0.35, "valence": 0.55, "genres": {"Indie": 2, "R&B": 2, "Pop": 1}, "moods": {"Chill": 3}}},
            {"label": "Late-night drive — window down, deep playlist", "w": {"energy": 0.55, "valence": 0.30, "genres": {"R&B": 2, "Indie": 2, "Hip-Hop": 1, "Pop": 1}, "moods": {"Chill": 2, "Sad": 1}}},
            {"label": "Studying / focused — headphones in",            "w": {"energy": 0.20, "valence": 0.35, "genres": {"Classical": 3, "Jazz": 2, "Electronic": 1}, "moods": {"Focus": 3}}},
        ],
    },
    {
        "title": "Pick your drink",
        "options": [
            {"label": "Iced coffee — caffeinated and ready",   "w": {"energy": 0.75, "valence": 0.65, "genres": {"Pop": 2, "Hip-Hop": 2}, "moods": {"Energetic": 2, "Happy": 1}}},
            {"label": "Hot tea — slow morning, gentle",         "w": {"energy": 0.25, "valence": 0.55, "genres": {"Indie": 2, "Classical": 2, "Jazz": 1}, "moods": {"Chill": 2, "Focus": 1}}},
            {"label": "Cocktail — it's the weekend",            "w": {"energy": 0.85, "valence": 0.70, "genres": {"Electronic": 3, "Pop": 2, "R&B": 1}, "moods": {"Energetic": 2}}},
            {"label": "Just water — locked in, focused",        "w": {"energy": 0.20, "valence": 0.40, "genres": {"Classical": 2, "Jazz": 2, "Indie": 1}, "moods": {"Focus": 3}}},
        ],
    },
    {
        "title": "Your texting style is…",
        "options": [
            {"label": "lol same all lowercase — vibes only",                  "w": {"energy": 0.55, "valence": 0.65, "genres": {"Indie": 2, "Pop": 2}, "moods": {"Chill": 2, "Happy": 1}}},
            {"label": "Perfect grammar. With periods.",                       "w": {"energy": 0.30, "valence": 0.45, "genres": {"Classical": 2, "Jazz": 2, "Indie": 1}, "moods": {"Focus": 3}}},
            {"label": "Voice memos, mostly — talking is faster",              "w": {"energy": 0.85, "valence": 0.75, "genres": {"Hip-Hop": 3, "Pop": 2, "Rock": 1}, "moods": {"Energetic": 3, "Happy": 1}}},
            {"label": "17-paragraph essays — feelings need full context",     "w": {"energy": 0.45, "valence": 0.30, "genres": {"Indie": 3, "R&B": 2, "Classical": 1}, "moods": {"Sad": 2, "Chill": 1}}},
        ],
    },
    {
        "title": "What is the weather inside your head right now?",
        "options": [
            {"label": "Sunny — everything's clicking",     "w": {"energy": 0.75, "valence": 0.95, "genres": {"Pop": 2, "Indie": 1}, "moods": {"Happy": 3}}},
            {"label": "Cloudy — vibes, but soft",          "w": {"energy": 0.45, "valence": 0.50, "genres": {"Indie": 2, "R&B": 2}, "moods": {"Chill": 3}}},
            {"label": "Stormy — big mood, lots of energy", "w": {"energy": 0.90, "valence": 0.40, "genres": {"Rock": 3, "Hip-Hop": 2, "Electronic": 1}, "moods": {"Energetic": 3}}},
            {"label": "Rainy — in my feelings",            "w": {"energy": 0.30, "valence": 0.15, "genres": {"Indie": 2, "R&B": 2, "Classical": 1}, "moods": {"Sad": 3}}},
        ],
    },
    {
        "title": "At a party, you're usually…",
        "options": [
            {"label": "On the dance floor — losing earrings to the rhythm",       "w": {"energy": 0.95, "valence": 0.85, "genres": {"Electronic": 3, "Pop": 2, "Hip-Hop": 2}, "moods": {"Energetic": 3, "Happy": 2}}},
            {"label": "Deep in the kitchen — life-changing chats with strangers", "w": {"energy": 0.40, "valence": 0.55, "genres": {"Indie": 2, "R&B": 2, "Jazz": 2}, "moods": {"Chill": 3}}},
            {"label": "On aux duty — DJ unprovoked, no skips allowed",            "w": {"energy": 0.75, "valence": 0.70, "genres": {"Hip-Hop": 3, "Electronic": 2, "Pop": 2}, "moods": {"Energetic": 2, "Happy": 1}}},
            {"label": "Already left — bed always wins, no notes",                 "w": {"energy": 0.25, "valence": 0.35, "genres": {"Indie": 2, "Classical": 2, "R&B": 1}, "moods": {"Chill": 1, "Sad": 2, "Focus": 1}}},
        ],
    },
]

print(f"Quiz has {len(quiz)} questions.")

"""## 4. Recommendation logic

Three small functions:

1. **`aggregate_profile`** — turn the user's answers into a single musical profile (target energy, target valence, genre weights, mood weights).
2. **`score_song`** — compute a match score for one song against that profile. Songs whose energy and valence are close to the target score higher; the bonus terms reward matching genre and mood.
3. **`recommend`** — score every song in the dataset, sort, and return the top pick + a small playlist.

A separate **`pick_persona`** function picks a fun, descriptive name for the user's overall vibe based on their target energy and valence.

"""

def aggregate_profile(answers):
    """Build the user's musical profile from their quiz answers.

    `answers` is a dict: { question_index: option_index }.
    """
    energy_sum = 0.0
    valence_sum = 0.0
    weight_sum = 0
    genres = {}
    moods = {}

    for qi, ai in answers.items():
        opt = quiz[qi]["options"][ai]
        w = opt["w"]
        energy_sum  += w["energy"]
        valence_sum += w["valence"]
        weight_sum  += 1
        for g, v in w["genres"].items():
            genres[g] = genres.get(g, 0) + v
        for m, v in w["moods"].items():
            moods[m] = moods.get(m, 0) + v

    return {
        "target_energy":  energy_sum  / weight_sum if weight_sum else 0.5,
        "target_valence": valence_sum / weight_sum if weight_sum else 0.5,
        "genres": genres,
        "moods":  moods,
    }


def score_song(row, profile):
    """Higher score = better match for this user's profile."""
    energy_dist  = abs(row["energy"]  - profile["target_energy"])
    valence_dist = abs(row["valence"] - profile["target_valence"])
    genre_bonus  = profile["genres"].get(row["genre"], 0) * 0.08
    mood_bonus   = profile["moods"].get(row["mood"],  0) * 0.07
    pop_bonus    = row["popularity"] / 100.0 # Changed from 1000.0 to 100.0
    return -(energy_dist + valence_dist) + genre_bonus + mood_bonus + pop_bonus


def recommend(answers, songs_df=songs, k=6):
    """Return (profile, top_pick_row, playlist_dataframe)."""
    profile = aggregate_profile(answers)
    scored  = songs_df.copy()
    scored["match_score"] = scored.apply(lambda r: score_song(r, profile), axis=1)
    scored = scored.sort_values("match_score", ascending=False)
    return profile, scored.iloc[0], scored.head(k)


def pick_persona(profile):
    """Map the (energy, valence) target to a fun persona title + description."""
    e = profile["target_energy"]
    v = profile["target_valence"]

    if e >= 0.78 and v >= 0.78:
        return ("The Disco Heart",
                "Pure joy at full volume. You'd dance in an empty parking lot if the song hit.")
    if e >= 0.65 and v >= 0.55:
        return ("The Main-Character Anthem",
                "High energy, high serotonin. You walk into rooms like there's a soundtrack playing.")
    if e >= 0.65 and v < 0.55:
        return ("The Midnight Hype",
                "Loud, sharp, a little dark — your playlist hits like 1am in a cab.")
    if e >= 0.45 and v >= 0.65:
        return ("The Golden Hour",
                "Warm, sun-through-the-trees energy. Walks home with a small smile.")
    if e < 0.45 and v >= 0.55:
        return ("The Sunset Daydreamer",
                "Soft, warm, daydream energy. Headphones in, eyes on the sky.")
    if e < 0.40 and v < 0.40:
        return ("The Rainy-Window Romantic",
                "In your feelings, in the best way. A movie scene about you, scored just right.")
    if e < 0.40:
        return ("The Library Loft",
                "Focused, quiet, thinking ten thoughts at once. Music as the background of your brain.")
    if v < 0.40:
        return ("The Slow Burn",
                "Brooding without being heavy. The friend people call when they need to vent.")
    return ("The Easy Drift",
            "Steady mood, easy tempo. Your playlist just works for everything.")

"""## 5. Real album art + 30-second preview (iTunes Search API)

Apple's iTunes Search API is **free, no auth, CORS-friendly**, and returns the album cover plus a 30-second mp3 preview for most popular songs. We use it for the *top pick* so the recommendation feels like a real Spotify-style product.

Endpoint:
`https://itunes.apple.com/search?term=<song+artist>&media=music&entity=song&limit=1`

"""

def fetch_song_meta(name, artist, timeout=5):
    """Fetch real cover art URL + 30-second preview URL from iTunes.

    Returns a dict {"cover": ..., "preview": ...} or None if the song isn't found.
    """
    try:
        resp = requests.get(
            "https://itunes.apple.com/search",
            params={
                "term": f"{name} {artist}",
                "media": "music",
                "entity": "song",
                "limit": 1,
            },
            timeout=timeout,
        )
        resp.raise_for_status()
        items = resp.json().get("results", [])
        if not items:
            return None
        item = items[0]
        cover = item.get("artworkUrl100", "")
        if cover:
            cover = cover.replace("100x100bb", "600x600bb")
        return {
            "cover":   cover or None,
            "preview": item.get("previewUrl") or None,
        }
    except Exception as e:
        print("iTunes lookup failed:", e)
        return None


# Quick smoke test
fetch_song_meta("Blinding Lights", "The Weeknd")

"""## 6. Display helpers — turn results into a nice card

We use HTML inside the notebook to render a styled "recommendation card" with the album cover, song info, persona, and explanation. The 30-second preview is played with `IPython.display.Audio`.

"""

def render_persona_card(name, persona_title, persona_desc, profile):
    top_mood  = max(profile["moods"].items(),  key=lambda kv: kv[1])[0] if profile["moods"]  else "Chill"
    top_genre = max(profile["genres"].items(), key=lambda kv: kv[1])[0] if profile["genres"] else "Pop"
    return f"""
    <div style="padding:22px;border-radius:14px;
                background:linear-gradient(135deg,#163826 0%,#1a2030 60%,#2b1d3a 100%);
                color:#eceff4;text-align:center;margin:14px 0;">
      <p style="color:#6ee7a7;font-size:0.78rem;font-weight:800;letter-spacing:1.5px;
                text-transform:uppercase;margin:0 0 6px 0;">
        {name}'s vibe
      </p>
      <h2 style="margin:4px 0 8px 0;font-size:1.7rem;">{persona_title}</h2>
      <p style="margin:0 0 14px 0;color:#cbd5e1;">{persona_desc}</p>
      <div>
        <span style="padding:4px 12px;border-radius:999px;background:rgba(29,185,84,0.15);
                     border:1px solid rgba(110,231,167,0.4);color:#6ee7a7;
                     font-size:0.78rem;font-weight:600;margin:0 4px;">Mood · {top_mood}</span>
        <span style="padding:4px 12px;border-radius:999px;background:rgba(29,185,84,0.15);
                     border:1px solid rgba(110,231,167,0.4);color:#6ee7a7;
                     font-size:0.78rem;font-weight:600;margin:0 4px;">Genre · {top_genre}</span>
        <span style="padding:4px 12px;border-radius:999px;background:rgba(255,255,255,0.06);
                     border:1px solid #2a2f3a;color:#cbd5e1;
                     font-size:0.78rem;font-weight:600;margin:0 4px;">Energy {profile['target_energy']:.2f}</span>
        <span style="padding:4px 12px;border-radius:999px;background:rgba(255,255,255,0.06);
                     border:1px solid #2a2f3a;color:#cbd5e1;
                     font-size:0.78rem;font-weight:600;margin:0 4px;">Valence {profile['target_valence']:.2f}</span>
      </div>
    </div>
    """


def render_top_pick_card(top, meta):
    cover_html = ""
    if meta and meta.get("cover"):
        cover_html = (
            f'<img src="{meta["cover"]}" alt="album cover" '
            f'style="width:160px;height:160px;border-radius:12px;display:block;'
            f'margin:0 auto 14px;box-shadow:0 8px 22px rgba(0,0,0,0.35);" />'
        )
    return f"""
    <div style="padding:22px;border:1px solid #2a2f3a;border-radius:14px;
                background:#1a1d24;color:#eceff4;text-align:center;margin:14px 0;">
      <p style="color:#1ed760;font-size:0.78rem;font-weight:800;letter-spacing:1.5px;
                text-transform:uppercase;margin:0 0 8px 0;">Your top pick</p>
      {cover_html}
      <h3 style="margin:0 0 4px 0;font-size:1.4rem;">{top['name']}</h3>
      <p style="margin:0 0 12px 0;color:#9ca3af;">by {top['artist']}</p>
      <div>
        <span style="padding:4px 12px;border-radius:999px;background:rgba(29,185,84,0.10);
                     border:1px solid rgba(110,231,167,0.4);color:#6ee7a7;
                     font-size:0.78rem;font-weight:600;margin:0 4px;">{top['genre']}</span>
        <span style="padding:4px 12px;border-radius:999px;background:rgba(29,185,84,0.10);
                     border:1px solid rgba(110,231,167,0.4);color:#6ee7a7;
                     font-size:0.78rem;font-weight:600;margin:0 4px;">{top['mood']}</span>
        <span style="padding:4px 12px;border-radius:999px;background:rgba(255,255,255,0.06);
                     border:1px solid #2a2f3a;color:#cbd5e1;
                     font-size:0.78rem;font-weight:600;margin:0 4px;">Energy {top['energy']:.2f}</span>
        <span style="padding:4px 12px;border-radius:999px;background:rgba(255,255,255,0.06);
                     border:1px solid #2a2f3a;color:#cbd5e1;
                     font-size:0.78rem;font-weight:600;margin:0 4px;">{int(top['tempo'])} BPM</span>
      </div>
    </div>
    """


def build_explanation(top, profile):
    return (
        f"<p><b>Why this one?</b> Your vibe profile averaged out to "
        f"<b>energy {profile['target_energy']:.2f}</b> and "
        f"<b>valence {profile['target_valence']:.2f}</b>. "
        f"<b>{top['name']}</b> by <b>{top['artist']}</b> sits at energy "
        f"{top['energy']:.2f} / valence {top['valence']:.2f}, with a "
        f"genre and mood that match your top picks "
        f"({top['genre']} · {top['mood']}). It also has a "
        f"popularity of {int(top['popularity'])}/100, which is the tiebreaker.</p>"
    )

"""## 7. Build the interactive widgets

`ipywidgets` gives us a real, live UI inside the notebook — text input, dropdowns, and buttons. Changing a dropdown does not trigger anything until the user clicks **Get my vibe**, which then runs the recommendation pipeline and renders the result inside an `Output` widget.

"""

# --- Name input ---
name_input = widgets.Text(
    value="",
    placeholder="Type your name",
    description="Name:",
    style={"description_width": "120px"},
    layout=widgets.Layout(width="420px"),
)

# --- Build one Dropdown per quiz question ---
quiz_widgets = []
for i, q in enumerate(quiz):
    labels = ["—"] + [opt["label"] for opt in q["options"]]
    dd = widgets.Dropdown(
        options=labels,
        value="—",
        description=f"Q{i+1}:",
        style={"description_width": "60px"},
        layout=widgets.Layout(width="640px"),
    )
    # Stash the question text on the widget so we can show it as a label
    dd._q_title = q["title"]
    quiz_widgets.append(dd)

# --- Buttons ---
find_btn = widgets.Button(
    description="Get my vibe",
    button_style="success",
    icon="music",
    layout=widgets.Layout(width="200px", height="40px"),
)
reset_btn = widgets.Button(
    description="Reset",
    button_style="warning",
    layout=widgets.Layout(width="120px", height="40px"),
)

# --- Output area where recommendations appear ---
output_area = widgets.Output()

"""## 8. Wire up the buttons

When the user clicks **Get my vibe**:

1. Read the name and the dropdown selections.
2. Convert dropdown selections into the `{question_index: option_index}` dict the recommendation pipeline expects.
3. Run `recommend(...)` to get the profile, top pick, and playlist.
4. Pick a persona, fetch real album art + audio preview, and render everything.

"""

def on_find_clicked(_):
    with output_area:
        clear_output()

        name = name_input.value.strip() or "friend"

        # Collect answers, skipping any question the user left as "—"
        answers = {}
        for i, dd in enumerate(quiz_widgets):
            if dd.value == "—":
                continue
            labels = [opt["label"] for opt in quiz[i]["options"]]
            answers[i] = labels.index(dd.value)

        if not answers:
            display(HTML(
                "<p style='color:#b00020;'>Please answer at least one question, "
                "then click <b>Get my vibe</b> again.</p>"
            ))
            return

        # 1. Recommendation pipeline
        profile, top, playlist = recommend(answers)
        persona_title, persona_desc = pick_persona(profile)

        # 2. Real cover + preview from iTunes
        meta = fetch_song_meta(top["name"], top["artist"])

        # 3. Render — persona card, top pick card, explanation, playlist, audio
        display(HTML(render_persona_card(name, persona_title, persona_desc, profile)))
        display(HTML(render_top_pick_card(top, meta)))
        display(HTML(build_explanation(top, profile)))

        if meta and meta.get("preview"):
            display(HTML("<p><b>30-second preview:</b></p>"))
            display(Audio(url=meta["preview"], autoplay=False))
        else:
            display(HTML("<p style='color:#888;'><i>(Audio preview not available for this song.)</i></p>"))

        # 4. Playlist table
        display(HTML(f"<p><b>Your BACO Station playlist ({len(playlist)} tracks):</b></p>"))
        nice_cols = ["name", "artist", "genre", "mood", "energy", "valence", "tempo", "popularity"]
        display(playlist[nice_cols].reset_index(drop=True))


def on_reset_clicked(_):
    name_input.value = ""
    for dd in quiz_widgets:
        dd.value = "—"
    with output_area:
        clear_output()


find_btn.on_click(on_find_clicked)
reset_btn.on_click(on_reset_clicked)

"""## 9. Run the app

Type your name, answer as many of the **9 vibe questions** as you like, then click **Get my vibe**. The result includes:

- A persona ("The Disco Heart", "The Sunset Daydreamer", etc.)
- The top recommended song with its **real album cover** and a **30-second preview** you can play
- A short playlist of similar matches as a `pandas` DataFrame
- An explanation of why the song was picked

"""

header = widgets.HTML("""
<div style="padding:18px 22px;border-radius:12px;
            background:linear-gradient(120deg,#1db954 0%,#1ed760 50%,#14833b 100%);
            color:white;margin-bottom:10px;">
  <h2 style="margin:0;">BACO Station</h2>
  <p style="margin:4px 0 0 0;">Pick your mood, your genre, your energy — get songs that match.</p>
</div>
""")

# Show each question above its dropdown so users see the full question text.
labelled_questions = []
for dd in quiz_widgets:
    label = widgets.HTML(
        f"<p style='margin:14px 0 4px 0;font-weight:600;'>{dd._q_title}</p>"
    )
    labelled_questions.extend([label, dd])

inputs_box = widgets.VBox(
    [name_input] + labelled_questions,
    layout=widgets.Layout(
        padding="14px",
        border="1px solid #d0d7de",
        border_radius="10px",
        margin="10px 0",
    ),
)

buttons_box = widgets.HBox([find_btn, reset_btn])

app_ui = widgets.VBox([header, inputs_box, buttons_box, output_area])
display(app_ui)

"""## Optional — view the full dataset

This last cell is just for the demo / for the professor. It shows the full table the recommendation engine reads from, so it is clear that the app is really filtering real data and not printing fixed text.

"""

songs

"""## How to run this notebook

1. Open the notebook in **Jupyter Lab/Notebook** or **Google Colab**.
2. Run the cells in order from top to bottom.
3. In Section 9 (the "Run the app" cell), fill in your name, answer the questions, and click **Get my vibe**.
4. The persona, top pick, real album cover, audio preview, and playlist all appear under the buttons.
5. Click **Reset** to clear and try a new combination.

**Note for Google Colab:** if the widgets do not render, run this once at the top of the notebook:

```python
from google.colab import output
output.enable_custom_widget_manager()
```

---

*This is the Milestone 5 frontend prototype for the S2 BACO Station group. The next milestones will replace the in-notebook DataFrame with the full Spotify dataset and add a more advanced recommendation model.*

We also built a **web version** of this same prototype (HTML + CSS + JavaScript) with a vinyl record visualization, a 3D play button, smooth quiz transitions, and Hogwarts house crests as inline SVG. It uses the same iTunes API integration and the same scoring logic. Screenshots and a link are in our project document.

"""
